### ISSUE TITLE
ValueError: There is no such driver by url 

### ISSUE THREAD

**Issue by andreileonsalas** [jsoma/selenium-github-actions#4]
Hi, i just fork the repo and runned on github, but got this error:

`ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/105.0.5177/chromedriver_linux64.zip`

**Comment by jsoma** [comment]
Hooray, it's now fixed!

The issue was that Ubuntu comes with a version of Chromium – 105.0.5177 – that doesn't have a Selenium ChromeDriver. I [edited scrape.yml](https://github.com/jsoma/selenium-github-actions/commit/7eb3485e00b69eafdc45c1db3a946d797a80a613) and added the following lines:

```yaml
- name: Remove default Chromium
   run: sudo apt purge chromium-browser
- name: Install a new Chromium
   run: sudo apt install -y chromium-browser
```

By uninstalling the default Chronium and installing a new one it somehow magically works! I don't know if this is the best long-term solution, but it seems fine for now.
